package application;

public class Building {
	
	/**Building name*/
	private String name;
	
	/**Flavor text/useful information*/
	private String description;
	
	/**Current monetary cost of the building*/
	private int cost;
	
	/**Current population cost of the building*/
	private int popcost;
	
	/**Base gold income of the building*/
	private int gIncome;
	
	/**Base population income of the building*/
	private int pIncome;
	
	/**How much the building cost increases per building in the town*/
	private double costMultiplier;
	
	/**
	 * The type identifier for this building
	 * 1: Low-Income Housing
	 * 2: Med-Income Housing
	 * 3: High-Income Housing
	 * 4: Low-Income Industry
	 * 5: Med-Income Industry
	 * 6: High-Income Industry
	 * 
	 * TODO: 
	 * 7: Unique Buildings
	 * 8: National Wonders
	 * 9: World Wonders
	 */
	private int type;
	
	/**The number of this type of building in town*/
	private int count;
	
	/**To what degree this building affects the other types of buildings*/
	private double[] bonusFactor;
	
	public Building(String nName, String nDesc, int nCost, int pCost, int ngIncome,
			int npIncome, int nType, double[] nBonusFactor) {
		name = nName;
		description = nDesc;
		cost = nCost;
		popcost = pCost;
		gIncome = ngIncome;
		pIncome = npIncome;
		bonusFactor = nBonusFactor;
		
		type = nType;
		costMultiplier = 1.01;
		count = 0;
	}
	
	/**
	 * Method to buy a certain quantity of buildings
	 * @param quantity The number of buildings to be bought
	 * @param money The amount of money currently available
	 * @param people The number of people currently unemployed
	 */
	public void buyBuilding(int quantity, int money, int people) {
		for(int i = 0; i < quantity;i++) {
			if(money - cost >= 0 && people - popcost >= 0) {
				count++;
				money = money-cost;
				people = people-popcost;
				cost = (int)Math.ceil(cost*costMultiplier);
			}
		}
	}
	
	/**
	 * Method to buy the maximum amount of a given building given the current quantity of resources
	 * @param money The amount of money currently available
	 * @param people The number of people currently unemployed
	 */
	public void buyMax(int money, int people) {
		while(money-cost >= 0 && people -popcost >= 0) {
			count++;
			money = money - cost;
			people = people - popcost;
			cost = (int)Math.ceil(costMultiplier*cost);
		}
	}
	
	/**
	 * Method to get the gold income of this building type
	 * @return The amount of money generated by this building unadjusted for bonuses
	 */
	public int getGIncome() {
		return gIncome*count;
	}
	
	public int getPIncome() {
		return pIncome*count;
	}
	
	/**
	 * Method to get the name of the building
	 * @return the name of the building
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * Method which returns the type of the building for the purpose of calculating bonuses
	 * @return The building's type
	 */
	public int getType() {
		return type;
	}
	

	/**
	 * Method which returns the description/flavor text of the building
	 * @return The flavor text
	 */
	public String getDescription() {
		return description;
	}
}
